services:
  sftp:
    build: .
    env_file:
      - path: .env.public
      - path: .env.private
    ports:
      - 4893:8080
      - 4894:2022
      - 4895:8081
    volumes:
      - /mnt/md0:/srv/sftpgo
      - ./root/var/lib/sftpgo:/var/lib/sftpgo
    post_start:
      - command: lighttpd -f /var/lib/sftpgo/lighttpd.conf
